# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6e108f44558f10bf26a61794a1332357c461e630442e63cc47d5b5434d35d7d2f5dbf62f4586c9fb1b7e644e891db82869a3232ab66fa1eeea06e865b5dff3c

test:
  secret_key_base: 8a4d4a11e5e217b57cf143fec16c38244c26b4c24a7d40fb122a9c30949574e848b93ace7d22aaca1486c2e321da1c6e25af8d88f4f50c7c06089193573ae8ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
